language: node_js
sudo: required

node_js: stable
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install

script:
  - npm run build

after_script:
  - cd ./_book
  - git init
  - git config user.name "Yesterday17"
  - git config user.email "t@yesterday17.cn"
  - echo kyandy.mmf.moe > CNAME
  - git add .
  - git commit -m "Update GitBook By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://yesterday17:${CO_TOKEN}@${CO_REF}" master:master
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

# 环境变量
env:
  global:
    # Github Pages
    - GH_REF: github.com/Yesterday17/Kyandy
    # Coding Pages
    - CO_REF: git.dev.tencent.com/yesterday17/Kyandy.git
